# Generated by Django 3.1.2 on 2020-11-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
        ),
        migrations.RemoveField(
            model_name='account',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=50, verbose_name='Type'),
        ),
    ]
