# Generated by Django 3.1.2 on 2020-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='misha pidor', max_length=40, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='eto pravda', max_length=40, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='third_name',
            field=models.CharField(default='eshe on gay', max_length=40, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
