# Generated by Django 3.1.2 on 2020-11-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('task_text', models.TextField(verbose_name='Текст задания')),
                ('preview', models.CharField(max_length=250, verbose_name='Анонс задания')),
                ('tests', models.TextField(verbose_name='Тесты')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=3, verbose_name='Verdict')),
                ('last_test', models.IntegerField(verbose_name='lt test')),
                ('code', models.TextField(verbose_name='code')),
                ('lang', models.CharField(default='python3', max_length=10, verbose_name='lang')),
                ('runtime', models.FloatField(default=0, verbose_name='time')),
                ('date', models.DateField(verbose_name='date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
        ),
    ]
