# Generated by Django 3.1.2 on 2020-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='code',
            field=models.TextField(default='print(0', verbose_name='code'),
        ),
    ]
