# Generated by Django 3.1.2 on 2020-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tests',
            field=models.TextField(default='empty test', verbose_name='Тесты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(default='Задание', verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
