# Generated by Django 3.1.2 on 2020-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201101_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='code',
            field=models.TextField(default='code', verbose_name='code'),
        ),
    ]
