# Generated by Django 3.1.2 on 2020-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='account',
        ),
    ]
