# Generated by Django 3.1.2 on 2020-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_send_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='last_test',
            field=models.IntegerField(verbose_name='lt test'),
        ),
    ]
