# Generated by Django 3.1.2 on 2020-11-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_send_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='account',
        ),
    ]
