# Generated by Django 3.1.2 on 2020-11-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_send_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='lang',
            field=models.CharField(default=1, max_length=10, verbose_name='lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send',
            name='time',
            field=models.FloatField(default=0, verbose_name='time'),
            preserve_default=False,
        ),
    ]
