# Generated by Django 3.1.2 on 2020-11-01 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20201101_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send',
            old_name='time',
            new_name='runtime',
        ),
        migrations.AddField(
            model_name='send',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
